# -*- coding: utf-8 -*-
"""AverageCost.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16mpTrYMjRVWfRWLkUGRaa-AMN4-DOT9X
"""

import pandas as pd

#dataset.iloc[gets all rows , gets last column of data].get its values

dataset = pd.read_csv('Data1.csv')
X = dataset.iloc[:,-1].values

print(dataset)

print(X)

print("Average price is: ")
print(sum(X)/len(X))

